//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 6/25/2023 3:40:15 PM
namespace YogaManagement.Client.OdataClient.System
{
    /// <summary>
    /// There are no comments for DayOfWeek in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("DayOfWeek")]
    public enum DayOfWeek
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("Sunday")]
        Sunday = 0,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Monday")]
        Monday = 1,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Tuesday")]
        Tuesday = 2,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Wednesday")]
        Wednesday = 3,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Thursday")]
        Thursday = 4,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Friday")]
        Friday = 5,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Saturday")]
        Saturday = 6
    }
}
