//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 6/17/2023 8:41:25 PM
namespace YogaManagement.Client.OdataClient.YogaManagement.Contracts.MemberLevel
{
    /// <summary>
    /// There are no comments for MemberLevelDiscountDTOSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("MemberLevelDiscountDTOSingle")]
    public partial class MemberLevelDiscountDTOSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<MemberLevelDiscountDTO>
    {
        /// <summary>
        /// Initialize a new MemberLevelDiscountDTOSingle object.
        /// </summary>
        public MemberLevelDiscountDTOSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new MemberLevelDiscountDTOSingle object.
        /// </summary>
        public MemberLevelDiscountDTOSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new MemberLevelDiscountDTOSingle object.
        /// </summary>
        public MemberLevelDiscountDTOSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<MemberLevelDiscountDTO> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for MemberLevelDiscountDTO in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("MemberLevelDiscountDTO")]
    public partial class MemberLevelDiscountDTO : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new MemberLevelDiscountDTO object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="silver">Initial value of Silver.</param>
        /// <param name="gold">Initial value of Gold.</param>
        /// <param name="platinum">Initial value of Platinum.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static MemberLevelDiscountDTO CreateMemberLevelDiscountDTO(int ID, double silver, double gold, double platinum)
        {
            MemberLevelDiscountDTO memberLevelDiscountDTO = new MemberLevelDiscountDTO();
            memberLevelDiscountDTO.Id = ID;
            memberLevelDiscountDTO.Silver = silver;
            memberLevelDiscountDTO.Gold = gold;
            memberLevelDiscountDTO.Platinum = platinum;
            return memberLevelDiscountDTO;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Id is required.")]
        public virtual int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Silver in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Silver")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Silver is required.")]
        public virtual double Silver
        {
            get
            {
                return this._Silver;
            }
            set
            {
                this.OnSilverChanging(value);
                this._Silver = value;
                this.OnSilverChanged();
                this.OnPropertyChanged("Silver");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private double _Silver;
        partial void OnSilverChanging(double value);
        partial void OnSilverChanged();
        /// <summary>
        /// There are no comments for Property Gold in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Gold")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Gold is required.")]
        public virtual double Gold
        {
            get
            {
                return this._Gold;
            }
            set
            {
                this.OnGoldChanging(value);
                this._Gold = value;
                this.OnGoldChanged();
                this.OnPropertyChanged("Gold");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private double _Gold;
        partial void OnGoldChanging(double value);
        partial void OnGoldChanged();
        /// <summary>
        /// There are no comments for Property Platinum in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Platinum")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Platinum is required.")]
        public virtual double Platinum
        {
            get
            {
                return this._Platinum;
            }
            set
            {
                this.OnPlatinumChanging(value);
                this._Platinum = value;
                this.OnPlatinumChanged();
                this.OnPropertyChanged("Platinum");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private double _Platinum;
        partial void OnPlatinumChanging(double value);
        partial void OnPlatinumChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
