//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 6/25/2023 3:40:15 PM
namespace YogaManagement.Client.OdataClient.YogaManagement.Contracts.YogaClass
{
}
namespace YogaManagement.Client.OdataClient.YogaManagement.Contracts.Authority
{
}
namespace YogaManagement.Client.OdataClient.YogaManagement.Contracts.Course
{
}
namespace YogaManagement.Client.OdataClient.YogaManagement.Contracts.Category
{
}
namespace YogaManagement.Client.OdataClient.YogaManagement.Contracts.Enrollment
{
}
namespace YogaManagement.Client.OdataClient.YogaManagement.Contracts.TeacherEnrollment
{
}
namespace YogaManagement.Client.OdataClient.YogaManagement.Contracts.MemberLevel
{
}
namespace YogaManagement.Client.OdataClient.YogaManagement.Contracts.TimeSlot
{
}
namespace YogaManagement.Client.OdataClient.YogaManagement.Contracts.Wallet
{
}
namespace YogaManagement.Client.OdataClient.YogaManagement.Contracts.Transaction
{
}
namespace YogaManagement.Client.OdataClient.System
{
}
namespace YogaManagement.Client.OdataClient.Default
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Container")]
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public Container(global::System.Uri serviceRoot) :
                this(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
        }

        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public Container(global::System.Uri serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion protocolVersion) :
                base(serviceRoot, protocolVersion)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "YogaManagement.Contracts.TeacherEnrollment", "YogaManagement.Client.OdataClient.YogaManagement.Contracts.TeacherEnrollment");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "YogaManagement.Contracts.MemberLevel", "YogaManagement.Client.OdataClient.YogaManagement.Contracts.MemberLevel");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "YogaManagement.Contracts.Transaction", "YogaManagement.Client.OdataClient.YogaManagement.Contracts.Transaction");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "YogaManagement.Contracts.Enrollment", "YogaManagement.Client.OdataClient.YogaManagement.Contracts.Enrollment");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "YogaManagement.Contracts.Authority", "YogaManagement.Client.OdataClient.YogaManagement.Contracts.Authority");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "YogaManagement.Contracts.YogaClass", "YogaManagement.Client.OdataClient.YogaManagement.Contracts.YogaClass");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "YogaManagement.Contracts.Category", "YogaManagement.Client.OdataClient.YogaManagement.Contracts.Category");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "YogaManagement.Contracts.TimeSlot", "YogaManagement.Client.OdataClient.YogaManagement.Contracts.TimeSlot");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "YogaManagement.Contracts.Course", "YogaManagement.Client.OdataClient.YogaManagement.Contracts.Course");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "YogaManagement.Contracts.Wallet", "YogaManagement.Client.OdataClient.YogaManagement.Contracts.Wallet");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Default", "YogaManagement.Client.OdataClient.Default");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "System", "YogaManagement.Client.OdataClient.System");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("YogaManagement.Client.OdataClient.YogaManagement.Contracts.TeacherEnrollment", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("YogaManagement.Contracts.TeacherEnrollment.", originalNameAttribute.OriginalName);
                }
                return string.Concat("YogaManagement.Contracts.TeacherEnrollment.", clientType.Name);
            }
            if (clientType.Namespace.Equals("YogaManagement.Client.OdataClient.YogaManagement.Contracts.MemberLevel", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("YogaManagement.Contracts.MemberLevel.", originalNameAttribute.OriginalName);
                }
                return string.Concat("YogaManagement.Contracts.MemberLevel.", clientType.Name);
            }
            if (clientType.Namespace.Equals("YogaManagement.Client.OdataClient.YogaManagement.Contracts.Transaction", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("YogaManagement.Contracts.Transaction.", originalNameAttribute.OriginalName);
                }
                return string.Concat("YogaManagement.Contracts.Transaction.", clientType.Name);
            }
            if (clientType.Namespace.Equals("YogaManagement.Client.OdataClient.YogaManagement.Contracts.Enrollment", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("YogaManagement.Contracts.Enrollment.", originalNameAttribute.OriginalName);
                }
                return string.Concat("YogaManagement.Contracts.Enrollment.", clientType.Name);
            }
            if (clientType.Namespace.Equals("YogaManagement.Client.OdataClient.YogaManagement.Contracts.Authority", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("YogaManagement.Contracts.Authority.", originalNameAttribute.OriginalName);
                }
                return string.Concat("YogaManagement.Contracts.Authority.", clientType.Name);
            }
            if (clientType.Namespace.Equals("YogaManagement.Client.OdataClient.YogaManagement.Contracts.YogaClass", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("YogaManagement.Contracts.YogaClass.", originalNameAttribute.OriginalName);
                }
                return string.Concat("YogaManagement.Contracts.YogaClass.", clientType.Name);
            }
            if (clientType.Namespace.Equals("YogaManagement.Client.OdataClient.YogaManagement.Contracts.Category", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("YogaManagement.Contracts.Category.", originalNameAttribute.OriginalName);
                }
                return string.Concat("YogaManagement.Contracts.Category.", clientType.Name);
            }
            if (clientType.Namespace.Equals("YogaManagement.Client.OdataClient.YogaManagement.Contracts.TimeSlot", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("YogaManagement.Contracts.TimeSlot.", originalNameAttribute.OriginalName);
                }
                return string.Concat("YogaManagement.Contracts.TimeSlot.", clientType.Name);
            }
            if (clientType.Namespace.Equals("YogaManagement.Client.OdataClient.YogaManagement.Contracts.Course", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("YogaManagement.Contracts.Course.", originalNameAttribute.OriginalName);
                }
                return string.Concat("YogaManagement.Contracts.Course.", clientType.Name);
            }
            if (clientType.Namespace.Equals("YogaManagement.Client.OdataClient.YogaManagement.Contracts.Wallet", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("YogaManagement.Contracts.Wallet.", originalNameAttribute.OriginalName);
                }
                return string.Concat("YogaManagement.Contracts.Wallet.", clientType.Name);
            }
            if (clientType.Namespace.Equals("YogaManagement.Client.OdataClient.Default", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Default.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Default.", clientType.Name);
            }
            if (clientType.Namespace.Equals("YogaManagement.Client.OdataClient.System", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("System.", originalNameAttribute.OriginalName);
                }
                return string.Concat("System.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for YogaClasses in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("YogaClasses")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::YogaManagement.Client.OdataClient.YogaManagement.Contracts.YogaClass.YogaClassDTO> YogaClasses
        {
            get
            {
                if ((this._YogaClasses == null))
                {
                    this._YogaClasses = base.CreateQuery<global::YogaManagement.Client.OdataClient.YogaManagement.Contracts.YogaClass.YogaClassDTO>("YogaClasses");
                }
                return this._YogaClasses;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::YogaManagement.Client.OdataClient.YogaManagement.Contracts.YogaClass.YogaClassDTO> _YogaClasses;
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Users")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::YogaManagement.Client.OdataClient.YogaManagement.Contracts.Authority.UserDTO> Users
        {
            get
            {
                if ((this._Users == null))
                {
                    this._Users = base.CreateQuery<global::YogaManagement.Client.OdataClient.YogaManagement.Contracts.Authority.UserDTO>("Users");
                }
                return this._Users;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::YogaManagement.Client.OdataClient.YogaManagement.Contracts.Authority.UserDTO> _Users;
        /// <summary>
        /// There are no comments for Courses in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Courses")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::YogaManagement.Client.OdataClient.YogaManagement.Contracts.Course.CourseDTO> Courses
        {
            get
            {
                if ((this._Courses == null))
                {
                    this._Courses = base.CreateQuery<global::YogaManagement.Client.OdataClient.YogaManagement.Contracts.Course.CourseDTO>("Courses");
                }
                return this._Courses;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::YogaManagement.Client.OdataClient.YogaManagement.Contracts.Course.CourseDTO> _Courses;
        /// <summary>
        /// There are no comments for Categories in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Categories")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::YogaManagement.Client.OdataClient.YogaManagement.Contracts.Category.CategoryDTO> Categories
        {
            get
            {
                if ((this._Categories == null))
                {
                    this._Categories = base.CreateQuery<global::YogaManagement.Client.OdataClient.YogaManagement.Contracts.Category.CategoryDTO>("Categories");
                }
                return this._Categories;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::YogaManagement.Client.OdataClient.YogaManagement.Contracts.Category.CategoryDTO> _Categories;
        /// <summary>
        /// There are no comments for Enrollments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Enrollments")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::YogaManagement.Client.OdataClient.YogaManagement.Contracts.Enrollment.EnrollmentDTO> Enrollments
        {
            get
            {
                if ((this._Enrollments == null))
                {
                    this._Enrollments = base.CreateQuery<global::YogaManagement.Client.OdataClient.YogaManagement.Contracts.Enrollment.EnrollmentDTO>("Enrollments");
                }
                return this._Enrollments;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::YogaManagement.Client.OdataClient.YogaManagement.Contracts.Enrollment.EnrollmentDTO> _Enrollments;
        /// <summary>
        /// There are no comments for TeacherEnrollments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("TeacherEnrollments")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::YogaManagement.Client.OdataClient.YogaManagement.Contracts.TeacherEnrollment.TeacherEnrollmentDTO> TeacherEnrollments
        {
            get
            {
                if ((this._TeacherEnrollments == null))
                {
                    this._TeacherEnrollments = base.CreateQuery<global::YogaManagement.Client.OdataClient.YogaManagement.Contracts.TeacherEnrollment.TeacherEnrollmentDTO>("TeacherEnrollments");
                }
                return this._TeacherEnrollments;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::YogaManagement.Client.OdataClient.YogaManagement.Contracts.TeacherEnrollment.TeacherEnrollmentDTO> _TeacherEnrollments;
        /// <summary>
        /// There are no comments for MemberLevels in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("MemberLevels")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::YogaManagement.Client.OdataClient.YogaManagement.Contracts.MemberLevel.MemberLevelDiscountDTO> MemberLevelConditons
        {
            get
            {
                if ((this._MemberLevels == null))
                {
                    this._MemberLevels = base.CreateQuery<global::YogaManagement.Client.OdataClient.YogaManagement.Contracts.MemberLevel.MemberLevelDiscountDTO>("MemberLevels");
                }
                return this._MemberLevels;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::YogaManagement.Client.OdataClient.YogaManagement.Contracts.MemberLevel.MemberLevelDiscountDTO> _MemberLevels;
        /// <summary>
        /// There are no comments for MemberLevelConditons in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("MemberLevelConditons")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::YogaManagement.Client.OdataClient.YogaManagement.Contracts.MemberLevel.MemberLevelDiscountDTO> MemberLevelConditons
        {
            get
            {
                if ((this._MemberLevelConditons == null))
                {
                    this._MemberLevelConditons = base.CreateQuery<global::YogaManagement.Client.OdataClient.YogaManagement.Contracts.MemberLevel.MemberLevelDiscountDTO>("MemberLevelConditons");
                }
                return this._MemberLevelConditons;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::YogaManagement.Client.OdataClient.YogaManagement.Contracts.MemberLevel.MemberLevelDiscountDTO> _MemberLevelConditons;
        /// <summary>
        /// There are no comments for TimeSlots in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("TimeSlots")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::YogaManagement.Client.OdataClient.YogaManagement.Contracts.TimeSlot.TimeSlotDTO> TimeSlots
        {
            get
            {
                if ((this._TimeSlots == null))
                {
                    this._TimeSlots = base.CreateQuery<global::YogaManagement.Client.OdataClient.YogaManagement.Contracts.TimeSlot.TimeSlotDTO>("TimeSlots");
                }
                return this._TimeSlots;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::YogaManagement.Client.OdataClient.YogaManagement.Contracts.TimeSlot.TimeSlotDTO> _TimeSlots;
        /// <summary>
        /// There are no comments for Wallets in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Wallets")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::YogaManagement.Client.OdataClient.YogaManagement.Contracts.Wallet.WalletDTO> Wallets
        {
            get
            {
                if ((this._Wallets == null))
                {
                    this._Wallets = base.CreateQuery<global::YogaManagement.Client.OdataClient.YogaManagement.Contracts.Wallet.WalletDTO>("Wallets");
                }
                return this._Wallets;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::YogaManagement.Client.OdataClient.YogaManagement.Contracts.Wallet.WalletDTO> _Wallets;
        /// <summary>
        /// There are no comments for Transactions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Transactions")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::YogaManagement.Client.OdataClient.YogaManagement.Contracts.Transaction.TransactionDTO> Transactions
        {
            get
            {
                if ((this._Transactions == null))
                {
                    this._Transactions = base.CreateQuery<global::YogaManagement.Client.OdataClient.YogaManagement.Contracts.Transaction.TransactionDTO>("Transactions");
                }
                return this._Transactions;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::YogaManagement.Client.OdataClient.YogaManagement.Contracts.Transaction.TransactionDTO> _Transactions;
        /// <summary>
        /// There are no comments for YogaClasses in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToYogaClasses(global::YogaManagement.Client.OdataClient.YogaManagement.Contracts.YogaClass.YogaClassDTO yogaClassDTO)
        {
            base.AddObject("YogaClasses", yogaClassDTO);
        }
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToUsers(global::YogaManagement.Client.OdataClient.YogaManagement.Contracts.Authority.UserDTO userDTO)
        {
            base.AddObject("Users", userDTO);
        }
        /// <summary>
        /// There are no comments for Courses in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToCourses(global::YogaManagement.Client.OdataClient.YogaManagement.Contracts.Course.CourseDTO courseDTO)
        {
            base.AddObject("Courses", courseDTO);
        }
        /// <summary>
        /// There are no comments for Categories in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToCategories(global::YogaManagement.Client.OdataClient.YogaManagement.Contracts.Category.CategoryDTO categoryDTO)
        {
            base.AddObject("Categories", categoryDTO);
        }
        /// <summary>
        /// There are no comments for Enrollments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToEnrollments(global::YogaManagement.Client.OdataClient.YogaManagement.Contracts.Enrollment.EnrollmentDTO enrollmentDTO)
        {
            base.AddObject("Enrollments", enrollmentDTO);
        }
        /// <summary>
        /// There are no comments for TeacherEnrollments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToTeacherEnrollments(global::YogaManagement.Client.OdataClient.YogaManagement.Contracts.TeacherEnrollment.TeacherEnrollmentDTO teacherEnrollmentDTO)
        {
            base.AddObject("TeacherEnrollments", teacherEnrollmentDTO);
        }
        /// <summary>
        /// There are no comments for MemberLevels in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToMemberLevels(global::YogaManagement.Client.OdataClient.YogaManagement.Contracts.MemberLevel.MemberLevelDiscountDTO memberLevelDiscountDTO)
        {
            base.AddObject("MemberLevels", memberLevelDiscountDTO);
        }
        /// <summary>
        /// There are no comments for MemberLevelConditons in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToMemberLevelConditons(global::YogaManagement.Client.OdataClient.YogaManagement.Contracts.MemberLevel.MemberLevelDiscountDTO memberLevelDiscountDTO)
        {
            base.AddObject("MemberLevelConditons", memberLevelDiscountDTO);
        }
        /// <summary>
        /// There are no comments for TimeSlots in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToTimeSlots(global::YogaManagement.Client.OdataClient.YogaManagement.Contracts.TimeSlot.TimeSlotDTO timeSlotDTO)
        {
            base.AddObject("TimeSlots", timeSlotDTO);
        }
        /// <summary>
        /// There are no comments for Wallets in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToWallets(global::YogaManagement.Client.OdataClient.YogaManagement.Contracts.Wallet.WalletDTO walletDTO)
        {
            base.AddObject("Wallets", walletDTO);
        }
        /// <summary>
        /// There are no comments for Transactions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToTransactions(global::YogaManagement.Client.OdataClient.YogaManagement.Contracts.Transaction.TransactionDTO transactionDTO)
        {
            base.AddObject("Transactions", transactionDTO);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private const string filePath = @"OData ServiceCsdl.xml";

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader();
                try
                {
                    global::System.Collections.Generic.IEnumerable<global::Microsoft.OData.Edm.Validation.EdmError> errors;
                    global::Microsoft.OData.Edm.IEdmModel edmModel;

                    if (!global::Microsoft.OData.Edm.Csdl.CsdlReader.TryParse(reader, true, out edmModel, out errors))
                    {
	                    global::System.Text.StringBuilder errorMessages = new global::System.Text.StringBuilder();
	                    foreach (var error in errors)
	                    {
		                    errorMessages.Append(error.ErrorMessage);
		                    errorMessages.Append("; ");
	                    }
	                    throw new global::System.InvalidOperationException(errorMessages.ToString());
                    }

                    return edmModel;
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader()
            {
                try
                {
                    var assembly = global::System.Reflection.Assembly.GetExecutingAssembly();
                    var resourcePath = global::System.Linq.Enumerable.Single(assembly.GetManifestResourceNames(), str => str.EndsWith(filePath));
                    global::System.IO.Stream stream = assembly.GetManifestResourceStream(resourcePath);
                    return global::System.Xml.XmlReader.Create(new global::System.IO.StreamReader(stream));
                }
                catch(global::System.Xml.XmlException e)
                {
                    throw new global::System.Xml.XmlException("Failed to create an XmlReader from the stream. Check if the resource exists.", e);
                }
            }
        }
    }
}
