//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 6/26/2023 11:47:55 AM
namespace YogaManagement.Client.OdataClient.YogaManagement.Contracts.TimeSlot
{
    /// <summary>
    /// There are no comments for ScheduleDTOSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("ScheduleDTOSingle")]
    public partial class ScheduleDTOSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<ScheduleDTO>
    {
        /// <summary>
        /// Initialize a new ScheduleDTOSingle object.
        /// </summary>
        public ScheduleDTOSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ScheduleDTOSingle object.
        /// </summary>
        public ScheduleDTOSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ScheduleDTOSingle object.
        /// </summary>
        public ScheduleDTOSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<ScheduleDTO> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for ScheduleDTO in the schema.
    /// </summary>
    /// <KeyProperties>
    /// TimeSlotId
    /// YogaClassId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("TimeSlotId", "YogaClassId")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("ScheduleDTO")]
    public partial class ScheduleDTO : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ScheduleDTO object.
        /// </summary>
        /// <param name="timeSlotId">Initial value of TimeSlotId.</param>
        /// <param name="yogaClassId">Initial value of YogaClassId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static ScheduleDTO CreateScheduleDTO(int timeSlotId, int yogaClassId)
        {
            ScheduleDTO scheduleDTO = new ScheduleDTO();
            scheduleDTO.TimeSlotId = timeSlotId;
            scheduleDTO.YogaClassId = yogaClassId;
            return scheduleDTO;
        }
        /// <summary>
        /// There are no comments for Property TimeSlotId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("TimeSlotId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "TimeSlotId is required.")]
        public virtual int TimeSlotId
        {
            get
            {
                return this._TimeSlotId;
            }
            set
            {
                this.OnTimeSlotIdChanging(value);
                this._TimeSlotId = value;
                this.OnTimeSlotIdChanged();
                this.OnPropertyChanged("TimeSlotId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _TimeSlotId;
        partial void OnTimeSlotIdChanging(int value);
        partial void OnTimeSlotIdChanged();
        /// <summary>
        /// There are no comments for Property YogaClassId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("YogaClassId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "YogaClassId is required.")]
        public virtual int YogaClassId
        {
            get
            {
                return this._YogaClassId;
            }
            set
            {
                this.OnYogaClassIdChanging(value);
                this._YogaClassId = value;
                this.OnYogaClassIdChanged();
                this.OnPropertyChanged("YogaClassId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _YogaClassId;
        partial void OnYogaClassIdChanging(int value);
        partial void OnYogaClassIdChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
