//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 6/26/2023 11:47:55 AM
namespace YogaManagement.Client.OdataClient.YogaManagement.Contracts.TimeSlot
{
    /// <summary>
    /// There are no comments for TeacherScheduleDTOSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("TeacherScheduleDTOSingle")]
    public partial class TeacherScheduleDTOSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<TeacherScheduleDTO>
    {
        /// <summary>
        /// Initialize a new TeacherScheduleDTOSingle object.
        /// </summary>
        public TeacherScheduleDTOSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new TeacherScheduleDTOSingle object.
        /// </summary>
        public TeacherScheduleDTOSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new TeacherScheduleDTOSingle object.
        /// </summary>
        public TeacherScheduleDTOSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<TeacherScheduleDTO> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for TeacherScheduleDTO in the schema.
    /// </summary>
    /// <KeyProperties>
    /// TeacherProfileId
    /// TimeSlotId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("TeacherProfileId", "TimeSlotId")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("TeacherScheduleDTO")]
    public partial class TeacherScheduleDTO : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new TeacherScheduleDTO object.
        /// </summary>
        /// <param name="timeSlotId">Initial value of TimeSlotId.</param>
        /// <param name="teacherProfileId">Initial value of TeacherProfileId.</param>
        /// <param name="isTaken">Initial value of IsTaken.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static TeacherScheduleDTO CreateTeacherScheduleDTO(int timeSlotId, int teacherProfileId, bool isTaken)
        {
            TeacherScheduleDTO teacherScheduleDTO = new TeacherScheduleDTO();
            teacherScheduleDTO.TimeSlotId = timeSlotId;
            teacherScheduleDTO.TeacherProfileId = teacherProfileId;
            teacherScheduleDTO.IsTaken = isTaken;
            return teacherScheduleDTO;
        }
        /// <summary>
        /// There are no comments for Property TimeSlotId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("TimeSlotId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "TimeSlotId is required.")]
        public virtual int TimeSlotId
        {
            get
            {
                return this._TimeSlotId;
            }
            set
            {
                this.OnTimeSlotIdChanging(value);
                this._TimeSlotId = value;
                this.OnTimeSlotIdChanged();
                this.OnPropertyChanged("TimeSlotId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _TimeSlotId;
        partial void OnTimeSlotIdChanging(int value);
        partial void OnTimeSlotIdChanged();
        /// <summary>
        /// There are no comments for Property TeacherProfileId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("TeacherProfileId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "TeacherProfileId is required.")]
        public virtual int TeacherProfileId
        {
            get
            {
                return this._TeacherProfileId;
            }
            set
            {
                this.OnTeacherProfileIdChanging(value);
                this._TeacherProfileId = value;
                this.OnTeacherProfileIdChanged();
                this.OnPropertyChanged("TeacherProfileId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _TeacherProfileId;
        partial void OnTeacherProfileIdChanging(int value);
        partial void OnTeacherProfileIdChanged();
        /// <summary>
        /// There are no comments for Property IsTaken in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("IsTaken")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "IsTaken is required.")]
        public virtual bool IsTaken
        {
            get
            {
                return this._IsTaken;
            }
            set
            {
                this.OnIsTakenChanging(value);
                this._IsTaken = value;
                this.OnIsTakenChanged();
                this.OnPropertyChanged("IsTaken");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private bool _IsTaken;
        partial void OnIsTakenChanging(bool value);
        partial void OnIsTakenChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
