//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 6/25/2023 3:40:15 PM
namespace YogaManagement.Client.OdataClient.YogaManagement.Contracts.Wallet
{
    /// <summary>
    /// There are no comments for WalletDTOSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("WalletDTOSingle")]
    public partial class WalletDTOSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<WalletDTO>
    {
        /// <summary>
        /// Initialize a new WalletDTOSingle object.
        /// </summary>
        public WalletDTOSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new WalletDTOSingle object.
        /// </summary>
        public WalletDTOSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new WalletDTOSingle object.
        /// </summary>
        public WalletDTOSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<WalletDTO> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for WalletDTO in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("WalletDTO")]
    public partial class WalletDTO : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new WalletDTO object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="balance">Initial value of Balance.</param>
        /// <param name="isAdminWallet">Initial value of IsAdminWallet.</param>
        /// <param name="appUserId">Initial value of AppUserId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static WalletDTO CreateWalletDTO(int ID, double balance, bool isAdminWallet, int appUserId)
        {
            WalletDTO walletDTO = new WalletDTO();
            walletDTO.Id = ID;
            walletDTO.Balance = balance;
            walletDTO.IsAdminWallet = isAdminWallet;
            walletDTO.AppUserId = appUserId;
            return walletDTO;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Id is required.")]
        public virtual int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Balance in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Balance")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Balance is required.")]
        public virtual double Balance
        {
            get
            {
                return this._Balance;
            }
            set
            {
                this.OnBalanceChanging(value);
                this._Balance = value;
                this.OnBalanceChanged();
                this.OnPropertyChanged("Balance");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private double _Balance;
        partial void OnBalanceChanging(double value);
        partial void OnBalanceChanged();
        /// <summary>
        /// There are no comments for Property IsAdminWallet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("IsAdminWallet")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "IsAdminWallet is required.")]
        public virtual bool IsAdminWallet
        {
            get
            {
                return this._IsAdminWallet;
            }
            set
            {
                this.OnIsAdminWalletChanging(value);
                this._IsAdminWallet = value;
                this.OnIsAdminWalletChanged();
                this.OnPropertyChanged("IsAdminWallet");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private bool _IsAdminWallet;
        partial void OnIsAdminWalletChanging(bool value);
        partial void OnIsAdminWalletChanged();
        /// <summary>
        /// There are no comments for Property AppUserId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("AppUserId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "AppUserId is required.")]
        public virtual int AppUserId
        {
            get
            {
                return this._AppUserId;
            }
            set
            {
                this.OnAppUserIdChanging(value);
                this._AppUserId = value;
                this.OnAppUserIdChanged();
                this.OnPropertyChanged("AppUserId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _AppUserId;
        partial void OnAppUserIdChanging(int value);
        partial void OnAppUserIdChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
